- hosts: all
  remote_user: ron 
  sudo: yes 
  gather_facts: yes
  tasks:
      - name: Upgrade currently installed packages
        apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"

      - name: Install common packages
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
           - tree
           - aptitude
           - iftop
           - python-apt
           - curl
           - telnet
           - apt-transport-https

#     - name: Install Webmin keys
#       apt_key: url='http://www.webmin.com/jcameron-key.asc' state=present
#     - name: Install primary Webmin repository
#       apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' state=present 
#     - name: Install secondary Webmin repository
#       apt_repository: repo='deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' state=present 
#     - name: Install Webmin software
#       apt: name=webmin state=latest update_cache=true cache_valid_time=600

      - name: Add docker to hosts file
        shell: echo 192.168.1.233 docker | tee -a /etc/hosts 

- hosts: desktops
  remote_user: ron 
  sudo: yes 
  gather_facts: yes
  tasks:
      - name: Install WebUpd8 keys
        apt_key: state=present keyserver=keyserver.ubuntu.com id=EEA14886
      - name: Install WebUpd8 repository
        apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present
      - name: Automatically select the Oracle License
        shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
        changed_when: false
      - name: Install Oracle JDK 8 
        apt: name=oracle-java8-installer state=latest update_cache=true cache_valid_time=600
      - name: Set Oracle JDK 8 environment variables
        apt: name=oracle-java8-set-default state=latest update_cache=true cache_valid_time=600

- hosts: application-containers 
  tasks:
      - name: Install Docker keys
        apt_key: state=present keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      - name: Install Docker repository
        apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present
      - name: Install Docker 
        apt: name=lxc-docker state=latest update_cache=true cache_valid_time=600
      - name: Add vagrant to the docker group
        user: name=vagrant state=present groups=docker
      - name: Restart Docker 
        service: name=docker state=restarted 

- hosts: dekstops
  tasks:
      - name: Install desktop packages
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
           - wireshark
           - chromium-browser
#     - name: Create Software directory 
#       file: path=/home/vagrant/Software owner=vagrant group=vagrant state=directory mode=755
#     - name: Download IntelliJ IDEA 
#       get_url: url=http://download.jetbrains.com/idea/ideaIU-13.1.5.tar.gz dest=/tmp mode=444 
#     - name: Unpack IntelliJ IDEA 
#       unarchive: src=/tmp/ideaIU-13.1.5.tar.gz dest=/home/vagrant/Software copy=no 
#     - name: Soft-link IntelliJ 
#       file: src=/home/vagrant/Software/idea-IU-135.1289 path=/home/vagrant/Software/idea state=link
#     - name: Create Desktop directory 
#       file: path=/home/vagrant/Desktop owner=vagrant group=vagrant state=directory mode=755
#     - name: Copy desktop IntelliJ file  
#       copy: src=files/InjelliJ.desktop dest=/home/vagrant/Desktop/InjelliJ.desktop owner=vagrant group=vagrant backup=no
#     - name: Set permissions on the home directory 
#       file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory
