- hosts: all
  remote_user: rkurr 
  sudo: yes 
  gather_facts: no
  tasks:
      - name: Upgrade currently installed packages
        apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"
      - name: Install common packages
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
           - tree
           - aptitude
           - iftop
           - python-apt
           - curl
           - telnet
           - apt-transport-https
           - mercurial 
           - git 
           - nagios3 
           - munin 
           - boinc 

#     - name: Add touchpad to hosts file
#       shell: creates=/var/hosts-touchpad echo 192.168.1.150 touchpad | tee -a /etc/hosts ; touch /var/hosts-touchpad
#     - name: Add batcave to hosts file
#       shell: creates=/var/hosts-batcave echo 192.168.1.222 batcave | tee -a /etc/hosts ; touch /var/hosts-batcave
#     - name: Add stargate to hosts file
#       shell: creates=/var/hosts-stargate echo 192.168.1.227 stargate | tee -a /etc/hosts ; touch /var/hosts-stargate
#     - name: Add printer to hosts file
#       shell: creates=/var/hosts-printer echo 192.168.1.228 printer | tee -a /etc/hosts ; touch /var/hosts-printer
#     - name: Add atlantis to hosts file
#       shell: creates=/var/hosts-atlantis echo 192.168.1.229 atlantis | tee -a /etc/hosts ; touch /var/hosts-atlantis
#     - name: Add tivo to hosts file
#       shell: creates=/var/hosts-tivo echo 192.168.1.230 tivo | tee -a /etc/hosts ; touch /var/hosts-tivo
#     - name: Add glados to hosts file
#       shell: creates=/var/hosts-glados echo 192.168.1.231 glados | tee -a /etc/hosts ; touch /var/hosts-glados
#     - name: Add cortans to hosts file
#       shell: creates=/var/hosts-coranas echo 192.168.1.232 cortana | tee -a /etc/hosts ; touch /var/hosts-cortana
#     - name: Add docker to hosts file
#       shell: creates=/var/hosts-docker echo 192.168.1.233 docker | tee -a /etc/hosts ; touch /var/hosts-docker
#     - name: Add nas to hosts file
#       shell: creates=/var/hosts-nas echo 192.168.1.234 nas | tee -a /etc/hosts ; touch /var/hosts-nas
#     - name: Add pi to hosts file
#       shell: creates=/var/hosts-pi echo 192.168.1.235 pi | tee -a /etc/hosts ; touch /var/hosts-pi
#     - name: Add pi2 to hosts file
#       shell: creates=/var/hosts-pi2 echo 192.168.1.236 pi2 | tee -a /etc/hosts ; touch /var/hosts-pi2
#     - name: Add coreos to hosts file
#       shell: creates=/var/hosts-coreos echo 192.168.1.237 coreos | tee -a /etc/hosts ; touch /var/hosts-coreos

- hosts: desktops
  remote_user: rkurr 
  sudo: yes 
  gather_facts: no
  tasks:
        apt: "name={{ item }} state=present update_cache=true cache_valid_time=600"
        with_items:
           - wireshark
           - chromium-browser
           - dosbox 
           - xchat 
           - filezilla 
           - gimp 
           - gimp-data-extras 
           - xsane 
           - vlc 
           - vlc-plugin-pulse 
           - fbreader 
           - calibre 
           - qrencode 
           - gitk 
           - grsync 
           - usb-creator-gtk
           - gmtp
           - etherape
           - nmap
           - nmapfe
           - xubuntu-restricted-extras
           - boinc 
           - gnome-disk-utility 

      - name: Install Handbrake PPA 
        apt_repository: repo='ppa:stebbins/handbrake-releases' state=present
      - name: Install Handbrake CLI 
        apt: name=handbrake-cli state=latest update_cache=true cache_valid_time=600
      - name: Install Handbrake GUI 
        apt: name=handbrake-gtk state=latest update_cache=true cache_valid_time=600

